name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URI:           ${{ secrets.MONGO_URI }}
      MONGO_DBNAME:        ${{ secrets.MONGO_DBNAME }}
      SECRET_KEY:          ${{ secrets.SECRET_KEY }}
      FLASK_APP:           ${{ secrets.FLASK_APP }}
      FLASK_ENV:           ${{ secrets.FLASK_ENV }}
      FLASK_PORT:          ${{ secrets.FLASK_PORT }}
      MAIL_SERVER:         ${{ secrets.MAIL_SERVER }}
      MAIL_PORT:           ${{ secrets.MAIL_PORT }}
      MAIL_USE_TLS:        ${{ secrets.MAIL_USE_TLS }}
      MAIL_USERNAME:       ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD:       ${{ secrets.MAIL_PASSWORD }}
      MAIL_DEFAULT_SENDER: ${{ secrets.MAIL_DEFAULT_SENDER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --ignore-pipfile

      - name: Run pytest
        run: |
          pipenv run pytest --maxfail=1 --disable-warnings -q
